#!/bin/bash

GROUP="$1"
DATE="$2"

LOG_HOME="$(readlink -e ~/logs)"
echo "using $LOG_HOME for log root"

log_path="/logs/$GROUP/$DATE/json"

docker run -it --rm \
  -v $LOG_HOME:/logs \
  topstats:latest \
  python TW5_parse_top_stats_detailed.py -t "${DATE}-WvW-Raid-POGU" "${log_path}"